/** @type {import('tailwindcss').Config} */

export default {
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.{vue,js,ts}',
    './pages/**/*.{vue,js,ts}',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './nuxt.config.{js,ts}',
  ],
  safelist: [
    'bg-page-dark',
    'bg-page-mid',
    'bg-card-dark',
    'bg-screen-dark',
    'bg-footer-dark',
    'bg-nav-dark',
    'z-[999]',
    'top-[65px]',
    'w-[600px]',
    'h-[600px]',
    'w-[18px]',
    'h-[20px]',
    'max-w-[1000px]',
    'rounded-[3rem]',
    'rounded-[2.4rem]',
    'text-[9px]',
    'text-[10px]',
    'text-[11px]',
    'bg-[#345D9D]/10',
    'bg-[#345D9D]/20',
    'bg-[#345D9D]/30',
    'bg-[#F5F8FF]',
    'text-[#345D9D]',
    'border-[#345D9D]/40',
    'border-[#345D9D]/50',
    'hover:border-[#345D9D]/50',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', 'ui-sans-serif', 'system-ui'],
      },
      colors: {
        'page-dark': '#050a1a',
        'page-mid': '#070d1f',
        'card-dark': '#0d1530',
        'screen-dark': '#0a0f20',
        'footer-dark': '#030712',
      },
    },
  },
  plugins: [],
}
